spring.application.name=researchgenie-ai
server.port=${PORT:8080}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

gemini.api.key=AIzaSyCBLL4Qu1Q_POZSev1g69GH1YYfdpkHVsQ
